version: '2.4'

networks:
  backend:
    driver: bridge

services:

  zoidberg-cli:
    restart: unless-stopped
    build: ./docker/cli
    hostname: zoidberg-cli
    working_dir: /var/www/code
    volumes:
      - ./:/var/www/code
    environment:
      TZ: ${TZ:-US/Central}
    tty: true
    networks:
      - backend
